# Generated by Django 4.1.5 on 2023-07-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='date',
        ),
    ]
