# Generated by Django 4.1.5 on 2023-04-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_alter_field_name'),
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='fields',
            field=models.ManyToManyField(to='fields.field'),
        ),
    ]
