# Generated by Django 4.1.5 on 2023-05-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_alter_field_name'),
        ('children', '0002_alter_children_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='fields',
            field=models.ManyToManyField(blank=True, to='fields.field'),
        ),
    ]
