# Generated by Django 4.1.5 on 2023-02-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_alter_field_name'),
        ('children', '0001_initial'),
        ('cleaningfields', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cleaningfield',
            unique_together={('child', 'field')},
        ),
    ]
