# Generated by Django 4.1.5 on 2023-06-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
        ('children', '0001_initial'),
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill', models.DecimalField(decimal_places=2, max_digits=7)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.children')),
                ('field', models.ManyToManyField(blank=True, to='fields.field')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salary.salary')),
            ],
        ),
    ]
