# Generated by Django 4.1.5 on 2023-05-03 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        ('fields', '0002_alter_field_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.children')),
                ('field', models.ManyToManyField(to='fields.field')),
            ],
        ),
    ]
