# Generated by Django 4.1.5 on 2023-05-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_alter_field_name'),
        ('cleaningups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningup',
            name='field',
            field=models.ManyToManyField(blank=True, to='fields.field'),
        ),
    ]
